command: ["gunicorn", "-b", "0.0.0.0:$DATABRICKS_APP_PORT", "--timeout", "120", "--graceful-timeout", "120", "run:app"]

resources:
  - name: genie-space
    genie_space:
      id: "01f14e46b80d1101a3d8bca2bfaa81f1"
